export const provincias = [
    {key: "Ancón", label: "Ancón"},
    {key: "Ate", label: "Ate"},
    {key: "Barranco", label: "Barranco"},
    {key: "Breña", label: "Breña"},
    {key: "Carabayllo", label: "Carabayllo"},
    {key: "Chaclacayo", label: "Chaclacayo"},
    {key: "Chorrillos", label: "Chorrillos"},
    {key: "Cieneguilla", label: "Cieneguilla"},
    {key: "Comas", label: "Comas"},
    {key: "El Agustino", label: "El Agustino"},
    {key: "Independencia", label: "Independencia"},
    {key: "Jesús María", label: "Jesús María"},
    {key: "La Molina", label: "La Molina"},
    {key: "La Victoria", label: "La Victoria"},
    {key: "Lima", label: "Lima"},
    {key: "Lince", label: "Lince"},
    {key: "Los Olivos", label: "Los Olivos"},
    {key: "Lurigancho", label: "Lurigancho"},
    {key: "Lurín", label: "Lurín"},
    {key: "Magdalena del Mar", label: "Magdalena del Mar"},
    {key: "Miraflores", label: "Miraflores"},
    {key: "Pachacámac", label: "Pachacámac"},
    {key: "Pucusana", label: "Pucusana"},
    {key: "Pachacámac", label: "Pachacámac"},
    {key: "Pueblo Libre", label: "Pueblo Libre"},
    {key: "Puente Piedra", label: "Puente Piedra"},
    {key: "Punta Hermosa", label: "Punta Hermosa"},
    {key: "Punta Negra", label: "Punta Negra"},
    {key: "Rímac", label: "Rímac"},
    {key: "San Bartolo", label: "San Bartolo"},
    {key: "San Borja", label: "San Borja"},
    {key: "San Isidro", label: "San Isidro"},
    {key: "San Juan de Lurigancho", label: "San Juan de Lurigancho"},
    {key: "San Juan de Miraflores", label: "San Juan de Miraflores"},
    {key: "San Luis", label: "San Luis"},
    {key: "San Martín de Porres", label: "San Martín de Porres"},
    {key: "San Miguel", label: "San Miguel"},
    {key: "Santa Anita", label: "Santa Anita"},
    {key: "Santa María del Mar", label: "Santa María del Mar"},
    {key: "Santa Rosa", label: "Santa Rosa"},
    {key: "Santiago de Surco", label: "Santiago de Surco"},
    {key: "Surquillo", label: "Surquillo"},
    {key: "Villa El Salvador", label: "Villa El Salvador"},
    {key: "Villa María del Triunfo", label: "Villa María del Triunfo"},
    

  ];